-- AlterTable
ALTER TABLE "product_taxes" ADD COLUMN     "simpleTax" DOUBLE PRECISION,
ALTER COLUMN "icms" DROP NOT NULL,
ALTER COLUMN "ipi" DROP NOT NULL,
ALTER COLUMN "pis" DROP NOT NULL,
ALTER COLUMN "cofins" DROP NOT NULL;
